apiVersion: argoproj.io/v1alpine1
kind: Application
metadata:
  name: rdicidr-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ubaidullah776/Complete-Coding-Challenge.git
    targetRevision: HEAD
    path: k8
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - prunePropagatetionPolicy=foreground
      - PruneLast=true
    revisionHistoryLimit: 10
    